name: Deploy
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
permissions: {}
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # For peaceiris/actions-gh-pages
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
    - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
      with:
        node-version: '18.4.0'
        cache: 'yarn'
    - run: yarn install
    - run: yarn build
    - uses: peaceiris/actions-gh-pages@bd8c6b06eba6b3d25d72b7a1767993c0aeee42e7 # v3.9.2
      if: github.event_name != 'pull_request'
      with:
        github_token: ${{ github.token }}
        publish_dir: ./build
        destination_dir: ./docs
